
var cText=''
cText += "<table bgcolor='#D7DCE1' width='206' border='0' cellspacing='0' cellpadding='0' ID='Table1'>"
cText += "<tr>"
cText += "<td colspan=3><img SRC='images/left_toplink.jpg'></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td colspan=3><IMG src='images/prod_lefthead.jpg'></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='34' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 20px' src='images/icon_cir.gif' ></td>"
cText += "<td colspan=2 width='149' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'><b>"
cText += "<A class=brandtext1 href='systems.htm'>COMPUTER SYSTEMS</b></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif' ></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'>"
cText += "<A class=brandtext1 href='notebooks.htm'><b>NOTEBOOKS</b></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif' ></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'>"
cText += "<A class=brandtext1 href='servers.htm'><b>SERVERS</b></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif' ></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'>"
cText += "<A class=brandtext1 href='security-cameras.htm'><b>SECURITY CAMERAS</b></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif' ></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'>"
cText += "<A class=brandtext1 href='biometric-systems.htm'><b>BIOMETRIC SYSTEMS</b></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif' ></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'><b>PERIPHERALS</b></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='25' width='26'></td>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'>"
cText += "<A class=brandtext href='optical_drives.htm'>Optical Drives</A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'>"
cText += "<A class=brandtext href='webcameras.htm'>Web Cameras</A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'>"
cText += "<A class=brandtext href='printers.htm'>Printers</A></td>"
cText += "</tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'>"
cText += "<A class=brandtext href='epson.htm'>Dot Matrix Printers</A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'>"
cText += "<A class=brandtext href='scanners.htm'>Scanners</A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'>"
cText += "<A class=brandtext href='monitors.htm'>Monitors</A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'>"
cText += "<A class=brandtext href='external_storage.htm'>Portable Storage Devices</A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif' ></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'><b>NETWORKING</b></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='25' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'><font color=#055867>"
cText += "<A class=brandtext href='routers.htm'>Routers</font></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'><font color=#055867>"
cText += "<A class=brandtext href='switches.htm'>Switches</font></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'><font color=#055867>"
cText += "<A class=brandtext href='wirelessnetworks.htm'>Wireless Networks</font></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='10' width='26'></td>"
cText += "<td width='15' align='right' valign='center'><IMG style='MARGIN-TOP: 15px' src='images/icon_arrow.gif' ></td>"
cText += "<td width='164' class='normalt' style='PADDING-LEFT: 8px' valign='bottom'><font color=#055867>"
cText += "<A class=brandtext href='racks.htm'>Racks</font></A></td>"
cText += "</tr>"
cText += "<tr><td height='20'></td></tr>"
cText += "<tr>"
cText += "<td colspan=3><IMG src='images/serv_lefthead.jpg'></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='40' width='26' align='right' valign='center'><IMG src='images/icon_cir.gif'></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'>"
cText += "<A class=brandtext1 href='services_support.htm#p1'><b>ANNUAL MAINTENANCE CONTRACTS</b></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif' ></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'>"
cText += "<A class=brandtext1 href='services_support.htm#p2'><b>NETWORK</b></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif'></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'>"
cText += "<A class=brandtext1 href='services_support.htm#p3'><b>SERVER ADMINISTRATION</b></A></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td height='22' width='26' align='right' valign='center'><IMG style='MARGIN-TOP: 8px' src='images/icon_cir.gif'></td>"
cText += "<td colspan=2 width='179' style='PADDING-LEFT: 8px' class='normalt' valign='bottom'>"
cText += "<A class=brandtext1 href='services_support.htm#p4'><b>IT AUDIT SERVICES</b></A></td>"
cText += "</tr>"
cText += "<tr><td height='20'></td></tr>"
cText += "<tr>"
cText += "<td onMouseover=img_act('toc7') onMouseout=img_inact('toc7') colspan=3>"
cText += "<A href='testimonials.htm' ><IMG src='images/test_lefthead.jpg' border=0 name=toc7></a></td>"
cText += "</tr>"
cText += "<tr>"
cText += "<td colspan=3 height='50'></td>"
cText += "</tr>"
cText += "</table>"

document.write(cText)



